### ISSUE TITLE
WorldGuard: Change chat channel automatically

### ISSUE THREAD

**Issue by LaeDev** [sVoxelDev/sChat#40]
**Describe the solution you'd like**
I would like to have a function that creates a specific channel only when you enter a specific area in conjunction with the World Guard

**Comment by Silthus** [comment]
This is a great idea and I think I will add this in v1.0.0.
The idea is to create two custom flags for regions. One to enable a region specific chat and one to customize the display name of the chat channel.
As a bonus the region channels will be synchronized across all servers and worlds. So if you have two regions that are named the same and both have the chat channel enabled they will be put into the same channel.

**Comment by Silthus** [comment]
This was added with #52
