### ISSUE TITLE
Pinned Chat Channel

### ISSUE THREAD

**Issue by LaeDev** [sVoxelDev/sChat#41]
**Describe the solution you'd like**
I wish the chat channel was fixed and there was a function to stay in that channel without being able to move to another channel.

**Comment by Silthus** [comment]
I don't really understand the use case, or the problem and wanted solution.
What do you mean unable to switch? Do you simply mean you cannot leave it (this is possible by using the `force: true` option), or locked in that channel as a guest? In this case you could only create one channel and make the others protected to require a join permission.

Can you elaborate on the problem you are facing? Then we can look for a solution.

**Comment by LaeDev** [comment]
It means not only that you can't go out, but also that you can't change the channel. (Of course, I can get rid of all the other channels, but I uploaded it because I thought it would be good to put it as a function) :)

**Comment by Silthus** [comment]
Wouldn't negating the `schat.player.channel.join` permission solve this? Without this permission players cannot join channels.
