### ISSUE TITLE
String too big

### ISSUE THREAD

**Issue by ShortException** [sVoxelDev/sChat#55]
![image](https://user-images.githubusercontent.com/81281223/142903401-ef2c7435-fdee-4f11-847d-22de7d5695a0.png)

**Comment by Silthus** [comment]
How and when did this occur? Can you reproduce the stacktrace?

**Comment by RCUngegrieftHD** [comment]
I first dragged the plugin on it then rl then I dragged the depency plugin on because I had forgotten it then rl again then I wrote in the chat

**Comment by Silthus** [comment]
Does rl mean reload or restart? Reloading the server with `/reload` is a non supported behavior of almost all plugins and should never be used.
Can you reproduce the bug? If yes, how? Also please attach a `/wg report -p` or at least the `/version` output.
Thank you!
